11/30/2024 14:20:20 - WARNING - __main__ - Process rank: 0, device: cuda:0, n_gpu: 1, distributed training: False, 16-bits training: False
11/30/2024 14:20:20 - INFO - __main__ - Training/evaluation parameters Seq2SeqTrainingArguments(
_n_gpu=1,
accelerator_config={'split_batches': False, 'dispatch_batches': None, 'even_batches': True, 'use_seedable_sampler': True, 'non_blocking': False, 'gradient_accumulation_kwargs': None, 'use_configured_state': False},
adafactor=False,
adam_beta1=0.9,
adam_beta2=0.999,
adam_epsilon=1e-08,
auto_find_batch_size=False,
average_tokens_across_devices=False,
batch_eval_metrics=False,
bf16=False,
bf16_full_eval=False,
data_seed=None,
dataloader_drop_last=False,
dataloader_num_workers=8,
dataloader_persistent_workers=False,
dataloader_pin_memory=True,
dataloader_prefetch_factor=None,
ddp_backend=None,
ddp_broadcast_buffers=None,
ddp_bucket_cap_mb=None,
ddp_find_unused_parameters=None,
ddp_timeout=1800,
debug=[],
deepspeed=None,
disable_tqdm=False,
dispatch_batches=None,
do_eval=False,
do_predict=False,
do_train=False,
eval_accumulation_steps=None,
eval_delay=0,
eval_do_concat_batches=True,
eval_on_start=False,
eval_steps=None,
eval_strategy=IntervalStrategy.NO,
eval_use_gather_object=False,
evaluation_strategy=None,
fp16=False,
fp16_backend=auto,
fp16_full_eval=False,
fp16_opt_level=O1,
fsdp=[],
fsdp_config={'min_num_params': 0, 'xla': False, 'xla_fsdp_v2': False, 'xla_fsdp_grad_ckpt': False},
fsdp_min_num_params=0,
fsdp_transformer_layer_cls_to_wrap=None,
full_determinism=False,
generation_config=None,
generation_max_length=None,
generation_num_beams=1,
gradient_accumulation_steps=1,
gradient_checkpointing=False,
gradient_checkpointing_kwargs=None,
greater_is_better=None,
group_by_length=False,
half_precision_backend=auto,
hub_always_push=False,
hub_model_id=None,
hub_private_repo=False,
hub_strategy=HubStrategy.EVERY_SAVE,
hub_token=<HUB_TOKEN>,
ignore_data_skip=False,
include_for_metrics=[],
include_inputs_for_metrics=False,
include_num_input_tokens_seen=False,
include_tokens_per_second=False,
jit_mode_eval=False,
label_names=None,
label_smoothing_factor=0.0,
learning_rate=5e-05,
length_column_name=length,
load_best_model_at_end=False,
local_rank=0,
log_level=passive,
log_level_replica=warning,
log_on_each_node=True,
logging_dir=./common_voice_16_0_it_pseudo_labelled/runs/Nov30_14-19-36_g063.cluster,
logging_first_step=False,
logging_nan_inf_filter=True,
logging_steps=500,
logging_strategy=IntervalStrategy.STEPS,
lr_scheduler_kwargs={},
lr_scheduler_type=SchedulerType.LINEAR,
max_grad_norm=1.0,
max_steps=-1,
metric_for_best_model=None,
mp_parameters=,
neftune_noise_alpha=None,
no_cuda=False,
num_train_epochs=3.0,
optim=OptimizerNames.ADAMW_TORCH,
optim_args=None,
optim_target_modules=None,
output_dir=./common_voice_16_0_it_pseudo_labelled,
overwrite_output_dir=False,
past_index=-1,
per_device_eval_batch_size=64,
per_device_train_batch_size=8,
predict_with_generate=False,
prediction_loss_only=False,
push_to_hub=True,
push_to_hub_model_id=None,
push_to_hub_organization=None,
push_to_hub_token=<PUSH_TO_HUB_TOKEN>,
ray_scope=last,
remove_unused_columns=True,
report_to=['wandb'],
restore_callback_states_from_checkpoint=False,
resume_from_checkpoint=None,
run_name=./common_voice_16_0_it_pseudo_labelled,
save_on_each_node=False,
save_only_model=False,
save_safetensors=True,
save_steps=500,
save_strategy=IntervalStrategy.STEPS,
save_total_limit=None,
seed=42,
skip_memory_metrics=True,
sortish_sampler=False,
split_batches=None,
tf32=None,
torch_compile=False,
torch_compile_backend=None,
torch_compile_mode=None,
torch_empty_cache_steps=None,
torchdynamo=None,
tpu_metrics_debug=False,
tpu_num_cores=None,
use_cpu=False,
use_ipex=False,
use_legacy_prediction_loop=False,
use_liger_kernel=False,
use_mps_device=False,
warmup_ratio=0.0,
warmup_steps=0,
weight_decay=0.0,
)
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
           ^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/utils/py_utils.py", line 399, in _single_map_nested
    mapped = [_single_map_nested((function, v, batched, batch_size, types, None, True, None)) for v in pbar]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/utils/py_utils.py", line 399, in _single_map_nested
    mapped = [_single_map_nested((function, v, batched, batch_size, types, None, True, None)) for v in pbar]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/utils/py_utils.py", line 373, in _single_map_nested
    return function(data_struct)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/download/download_manager.py", line 229, in _download_single
    out = cached_path(url_or_filename, download_config=download_config)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/utils/file_utils.py", line 251, in cached_path
    output_path = ExtractManager(cache_dir=download_config.cache_dir).extract(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/utils/extract.py", line 48, in extract
    self.extractor.extract(input_path, output_path, extractor_format)
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/utils/extract.py", line 332, in extract
    return extractor.extract(input_path, output_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/utils/extract.py", line 126, in extract
    tar_file.extractall(output_path, members=TarExtractor.safemembers(tar_file, output_path))
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/tarfile.py", line 2302, in extractall
    self._extract_one(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/tarfile.py", line 2369, in _extract_one
    self._handle_fatal_error(e)
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/tarfile.py", line 2365, in _extract_one
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/tarfile.py", line 2448, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/tarfile.py", line 2494, in makefile
    with bltn_open(targetpath, "wb") as target:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 122] Disk quota exceeded: '/scratch/user/shwetimasakshi/hf_datasets/downloads/extracted/3d5b4e76a9193e09e56cab203985c30d381603b9a1e35d86efdbf736bc345093/it_train_1/common_voice_it_20250027.mp3'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/user/shwetimasakshi/distil-whisper/training/finetune_multilingual/run_pseudo_labelling.py", line 1029, in <module>
    main()
  File "/scratch/user/shwetimasakshi/distil-whisper/training/finetune_multilingual/run_pseudo_labelling.py", line 509, in main
    raw_datasets[split] = load_dataset(
                          ^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/load.py", line 2154, in load_dataset
    builder_instance.download_and_prepare(
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/builder.py", line 924, in download_and_prepare
    self._download_and_prepare(
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/builder.py", line 1648, in _download_and_prepare
    super()._download_and_prepare(
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/builder.py", line 978, in _download_and_prepare
    split_generators = self._split_generators(dl_manager, **split_generators_kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/hf_cache/modules/datasets_modules/datasets/mozilla-foundation--common_voice_16_1/b312fb39f411af1f8d68f7cf694b9448c1889752433e46c08551cb406734274a/common_voice_16_1.py", line 146, in _split_generators
    local_extracted_archive_paths = dl_manager.extract(archive_paths) if not dl_manager.is_streaming else {}
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/download/download_manager.py", line 299, in extract
    extracted_paths = map_nested(
                      ^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/utils/py_utils.py", line 528, in map_nested
    mapped = parallel_map(
             ^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/utils/experimental.py", line 41, in _inner_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/parallel/parallel.py", line 34, in parallel_map
    return _map_with_multiprocessing_pool(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/site-packages/datasets/parallel/parallel.py", line 69, in _map_with_multiprocessing_pool
    mapped = pool.map(single_map_nested_func, split_kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/user/shwetimasakshi/.conda/envs/gpt2_new/lib/python3.12/multiprocessing/pool.py", line 774, in get
    raise self._value
OSError: [Errno 122] Disk quota exceeded: '/scratch/user/shwetimasakshi/hf_datasets/downloads/extracted/3d5b4e76a9193e09e56cab203985c30d381603b9a1e35d86efdbf736bc345093/it_train_1/common_voice_it_20250027.mp3'
